springdoc:
  swagger-ui:
    urls:
      - name: Notification Service
        url: /notification/v3/api-docs
      - name: User Service
        url: /user/v3/api-docs

spring:
  cloud:
    gateway:
      routes:
        - id: notification-service
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/notification/**, /notification/v3/api-docs
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/user/**, /user/v3/api-docs
          filters:
            - StripPrefix=1

  application:
    name: APIGATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
